from pgdb import connect

stops_stops = [
    ['Hlavná stanica', 'Nám. Franza Liszta', 'Žilinská', 'STU', 'Vysoká', 'Poštová-Martinus', 'Šafárikovo nám.',
     'Sad Janka Kráľa', 'Farského', 'Jungmannova'],
    ['Jungmannova', 'Farského', 'Sad Janka Kráľa', 'Šafárikovo nám.', 'Námestie SNP', 'Poštová-Martinus', 'Vysoká',
     'STU', 'Žilinská', 'Nám. Franza Liszta', 'Hlavná stanica'],
    ['Hlavná stanica', 'Nám. Franza Liszta', 'Žilinská', 'Blumentál', 'Legionárska', 'Trnavské mýto', 'Odbojárov',
     'Nová doba', 'Polus City Center', 'Zátišie', 'ŽST Nové Mesto'],
    ['ŽST Nové Mesto', 'Zátišie', 'Polus City Center', 'Nová doba', 'Odbojárov', 'Trnavské mýto', 'Legionárska',
     'Blumentál', 'STU', 'Žilinská', 'Nám. Franza Liszta', 'Hlavná stanica'],
    ['Komisárky', 'Púchovská', 'Záhumenice-Drevona', 'Detvianska', 'Hybešova', 'Hečkova', 'Černockého', 'Pekná cesta',
     'Malé Krasňany', 'Vozovňa Krasňany', 'ŽST Vinohrady', 'Nám. Biely kríž', 'Mladá garda', 'Riazanská', 'Pionierska',
     'Ursínyho', 'Račianske mýto', 'Blumentál', 'Americké nám.', 'Mariánska', 'Kamenné nám.', 'Šafárikovo nám.',
     'Sad Janka Kráľa', 'Farského', 'Jungmannova'],
    ['Jungmannova', 'Farského', 'Sad Janka Kráľa', 'Šafárikovo nám.', 'Kamenné nám.', 'Mariánska', 'Americké nám.',
     'Blumentál', 'Račianske mýto', 'Ursínyho', 'Pionierska', 'Riazanská', 'Mladá garda', 'Nám. Biely kríž',
     'ŽST Vinohrady', 'Vozovňa Krasňany', 'Malé Krasňany', 'Pekná cesta', 'Černockého', 'Hečkova', 'Hybešova',
     'Detvianska', 'Záhumenice-Drevona', 'Púchovská', 'Komisárky'],
    ['Pri kríži', 'OD Saratov', 'Drobného', 'Alexyho', 'Švantnerova', 'Damborského', 'Horné Krčace', 'Dolné Krčace',
     'Karlova Ves', 'Borská', 'MiÚ Karlova Ves', 'Nad lúčkami', 'Segnerova', 'Jurigovo nám.', 'Molecova',
     'Botanická záhrada', 'Lafranconi', 'Park kultúry', 'Chatam Sófer', 'Most SNP', 'Šafárikovo nám.', 'Kamenné nám.',
     'Mariánska', 'Odborárske nám.', 'Legionárska', 'Trnavské mýto', 'Odbojárov', 'Nová doba', 'Polus City Center',
     'Zátišie', 'Odborárska', 'Magnetová', 'Jurajov dvor', 'PPA Controll', 'Shopping Palace', 'Zlaté piesky'],
    ['Zlaté piesky', 'Shopping Palace', 'PPA Controll', 'Jurajov dvor', 'Vozovňa Jurajov dvor', 'Magnetová',
     'Odborárska', 'Zátišie', 'Polus City Center', 'Nová doba', 'Odbojárov', 'Trnavské mýto', 'Legionárska',
     'Americké nám.', 'Mariánska', 'SND', 'Nám. Ľ. Štúra', 'Most SNP', 'Chatam Sófer', 'Park kultúry', 'Lafranconi',
     'Botanická záhrada', 'Molecova', 'Jurigovo nám.', 'Segnerova', 'Nad lúčkami', 'MiÚ Karlova Ves', 'Borská',
     'Karlova Ves', 'Dolné Krčace', 'Horné Krčace', 'Damborského', 'Švantnerova', 'Alexyho', 'Drobného', 'OD Saratov',
     'Pri kríži'],
    ['Pri kríži', 'OD Saratov', 'Drobného', 'Alexyho', 'Švantnerova', 'Damborského', 'Horné Krčace', 'Dolné Krčace',
     'Karlova Ves', 'Borská', 'MiÚ Karlova Ves', 'Nad lúčkami', 'Segnerova', 'Jurigovo nám.', 'Molecova',
     'Botanická záhrada', 'Lafranconi', 'Park kultúry', 'Kapucínska', 'Poštová-Martinus', 'Vysoká', 'Blumentál',
     'Račianske mýto', 'Ursínyho', 'Pionierska', 'Riazanská', 'Mladá garda', 'Nám. Biely kríž', 'ŽST Vinohrady',
     'Vozovňa Krasňany', 'Malé Krasňany', 'Pekná cesta', 'Černockého', 'Hečkova', 'Hybešova', 'Detvianska',
     'Záhumenice-Drevona', 'Púchovská', 'Komisárky'],
    ['Komisárky', 'Púchovská', 'Záhumenice-Drevona', 'Detvianska', 'Hybešova', 'Hečkova', 'Černockého', 'Pekná cesta',
     'Malé Krasňany', 'Vozovňa Krasňany', 'ŽST Vinohrady', 'Nám. Biely kríž', 'Mladá garda', 'Riazanská', 'Pionierska',
     'Ursínyho', 'Račianske mýto', 'Blumentál', 'STU', 'Vysoká', 'Poštová-Martinus', 'Kapucínska', 'Park kultúry',
     'Lafranconi', 'Botanická záhrada', 'Molecova', 'Jurigovo nám.', 'Segnerova', 'Nad lúčkami', 'MiÚ Karlova Ves',
     'Borská', 'Karlova Ves', 'Dolné Krčace', 'Horné Krčace', 'Damborského', 'Švantnerova', 'Alexyho', 'Drobného',
     'OD Saratov', 'Pri kríži'],
    ['Karlova Ves', 'Borská', 'MiÚ Karlova Ves', 'Nad lúčkami', 'Segnerova', 'Jurigovo nám.', 'Molecova',
     'Botanická záhrada', 'Lafranconi', 'Park kultúry', 'Chatam Sófer', 'Most SNP', 'Šafárikovo nám.'],
    ['Šafárikovo nám.', 'SND', 'Nám. Ľ. Štúra', 'Most SNP', 'Chatam Sófer', 'Park kultúry', 'Lafranconi',
     'Botanická záhrada', 'Molecova', 'Jurigovo nám.', 'Segnerova', 'Nad lúčkami', 'MiÚ Karlova Ves', 'Borská',
     'Karlova Ves'],
    ['Komisárky', 'Púchovská', 'Záhumenice-Drevona', 'Detvianska', 'Hybešova', 'Hečkova', 'Černockého', 'Pekná cesta',
     'Malé Krasňany', 'Vozovňa Krasňany', 'ŽST Vinohrady', 'Nám. Biely kríž', 'Mladá garda', 'Riazanská', 'Pionierska',
     'Ursínyho', 'Račianske mýto', 'Blumentál', 'Americké nám.', 'Mariánska', 'Námestie SNP'],
    ['Námestie SNP', 'Poštová-Martinus', 'Vysoká', 'Blumentál', 'Račianske mýto', 'Ursínyho', 'Pionierska', 'Riazanská',
     'Mladá garda', 'Nám. Biely kríž', 'ŽST Vinohrady', 'Vozovňa Krasňany', 'Malé Krasňany', 'Pekná cesta',
     'Černockého', 'Hečkova', 'Hybešova', 'Detvianska', 'Záhumenice-Drevona', 'Púchovská', 'Komisárky'],
    ['Nám. Ľ. Štúra', 'Šafárikovo nám.', 'Námestie SNP', 'Poštová-Martinus', 'Vysoká', 'Blumentál', 'Legionárska',
     'Trnavské mýto', 'Saleziáni', 'Slovanet', 'Nemocnica Ružinov', 'Herlianska-OC Retro', 'Tomášikova', 'Súmračná',
     'Chlumeckého', 'Astronomická'],
    ['Astronomická', 'Chlumeckého', 'Súmračná', 'Tomášikova', 'Herlianska-OC Retro', 'Nemocnica Ružinov', 'Slovanet',
     'Saleziáni', 'Trnavské mýto', 'Legionárska', 'Blumentál', 'STU', 'Vysoká', 'Poštová-Martinus', 'SND',
     'Nám. Ľ. Štúra'],
    ['Karlova Ves', 'Borská', 'MiÚ Karlova Ves', 'Nad lúčkami', 'Segnerova', 'Jurigovo nám.', 'Molecova',
     'Botanická záhrada', 'Lafranconi', 'Park kultúry', 'Kapucínska', 'Kamenné nám.', 'Mariánska', 'Odborárske nám.',
     'Legionárska', 'Trnavské mýto', 'Saleziáni', 'Slovanet', 'Nemocnica Ružinov', 'Herlianska-OC Retro', 'Tomášikova',
     'Súmračná', 'Chlumeckého', 'Astronomická'],
    ['Astronomická', 'Chlumeckého', 'Súmračná', 'Tomášikova', 'Herlianska-OC Retro', 'Nemocnica Ružinov', 'Slovanet',
     'Saleziáni', 'Trnavské mýto', 'Legionárska', 'Americké nám.', 'Mariánska', 'Námestie SNP', 'Kapucínska',
     'Park kultúry', 'Lafranconi', 'Botanická záhrada', 'Molecova', 'Jurigovo nám.', 'Segnerova', 'Nad lúčkami',
     'MiÚ Karlova Ves', 'Borská', 'Karlova Ves'],
    ['Kuklovská', 'ZŠ Majerníkova', 'Matejkova', 'Tománkova', 'Hany Meličkovej', 'Pri podchode', 'Janotova',
     'Molecova'],
    ['Molecova', 'Janotova', 'Pri podchode', 'Hany Meličkovej', 'Tománkova', 'Matejkova', 'ZŠ Majerníkova',
     'Kuklovská'],
    ['Lovinského', 'Vozovňa Hroboňova', 'Hroboňova', 'Sokolská', 'Nám. Franza Liszta', 'Karpatská', 'Račianske mýto',
     'Trnavské mýto', 'Jelačičova'],
    ['Jelačičova', 'Trnavské mýto', 'Račianske mýto', 'Karpatská', 'SAV', 'Sokolská', 'Hroboňova', 'Prokopa Veľkého',
     'Vozovňa Hroboňova', 'Lovinského'],
    ['Hlavná stanica', 'Nám. Franza Liszta', 'Karpatská', 'Račianske mýto', 'Trnavské mýto', 'Saleziáni', 'Trhovisko',
     'BBCČiližská', 'Žitavská', 'Dudvážska', 'Hronská', 'Toryská', 'Komárovská', 'Priekopnícka', 'Cintorín Vrakuňa',
     'Ríbezľová', 'Ondrejovova', 'Brodná', 'Gagarinova-Rádio Europa 2', 'Hraničná-OC Retro', 'Pažítková', 'Prievozská',
     'BBC1 Plus-Miletičova', 'Trenčianska', 'Trhovisko', 'Saleziáni', 'Trnavské mýto', 'Račianske mýto', 'Karpatská',
     'Hlavná stanica'],
    ['Nemocnica sv. Michala', 'Ul. Čiližská', 'Žitavská', 'Dudvážska', 'Hronská', 'Toryská', 'Komárovská',
     'Priekopnícka', 'Cintorín Vrakuňa', 'Ríbezľová', 'Ondrejovova', 'Brodná', 'Gagarinova-Rádio Europa 2',
     'Hraničná-OC Retro', 'Pažítková', 'Prievozská', 'BBC1 Plus-Miletičova', 'Novohradská', 'Svätoplukova',
     'Autobusová stanica', 'Cintorínska', 'Nemocnica sv. Michala'],
    ['Búdková', 'Červený kríž', 'Jančova', 'Radvanská', 'Inovecká', 'Hrad', 'Zámocká', 'Partizánska', 'Kozia',
     'Hodžovo nám.', 'Nám. slobody', 'Štefanovičova', 'Šancová', 'Tupého', 'Jeséniova', 'Čremchová', 'Husova',
     'Koliba'],
    ['Koliba', 'Husova', 'Čremchová', 'Jeséniova', 'Tupého', 'Šancová', 'Štefanovičova', 'Nám. slobody', 'Hodžovo nám.',
     'Kozia', 'Partizánska', 'Zámocká', 'Hrad', 'Inovecká', 'Radvanská', 'Hummelova', 'Červený kríž', 'Búdková'],
    ['Rádiová', 'Bulharská', 'Spoločenská', 'Hanácka', 'Slovinská', 'Trnavská', 'Sabinovská', 'Bajkalská',
     'Zimný štadión', 'Trnavské mýto', 'Račianske mýto', 'Karpatská', 'SAV', 'Sokolská', 'Stromová', 'Bárdošova',
     'Magurská', 'Nemocnica Kramáre', 'Pri Suchom mlyne', 'Hýrošova', 'Valašská'],
    ['Valašská', 'Pri Suchom mlyne', 'Nemocnica Kramáre', 'Magurská', 'Bárdošova', 'Sokolská', 'Nám. Franza Liszta',
     'Karpatská', 'Račianske mýto', 'Trnavské mýto', 'Zimný štadión', 'Bajkalská', 'Sabinovská', 'Trnavská',
     'Slovinská', 'Hanácka', 'Spoločenská', 'Bulharská', 'Rádiová'],
    ['Rádiová', 'Bulharská', 'Spoločenská', 'Hanácka', 'Slovinská', 'Trnavská', 'Sabinovská', 'Bajkalská',
     'Zimný štadión', 'Saleziáni', 'Kvačalova', 'Kulíškova', 'Cvernovka', 'Svätoplukova', 'Autobusová stanica',
     'Cintorínska', 'Nemocnica sv. Michala'],
    ['Nemocnica sv. Michala', 'Ul. 29. augusta', 'Autobusová stanica', 'Svätoplukova', 'Cvernovka', 'Kulíškova',
     'Kvačalova', 'Saleziáni', 'Zimný štadión', 'Bajkalská', 'Sabinovská', 'Trnavská', 'Slovinská', 'Hanácka',
     'Spoločenská', 'Bulharská', 'Rádiová'],
    ['ŽST Železná studienka', 'Patrónka', 'Hýrošova', 'Valašská', 'Lovinského', 'Vozovňa Hroboňova', 'Horský park',
     'Búdková', 'Červený kríž', 'Jančova', 'Radvanská', 'Inovecká', 'Hrad', 'Zámocká', 'Partizánska', 'Kozia',
     'Hodžovo nám.', 'Kollárovo nám.', 'Mickiewiczova', 'Karadžičova', 'Kvačalova', 'Saleziáni', 'Zimný štadión'],
    ['Zimný štadión', 'Saleziáni', 'Kvačalova', 'Karadžičova', 'Americké nám.', 'Kollárovo nám.', 'Hodžovo nám.',
     'Kozia', 'Partizánska', 'Zámocká', 'Hrad', 'Inovecká', 'Radvanská', 'Hummelova', 'Červený kríž', 'Búdková',
     'Horský park', 'Vozovňa Hroboňova', 'Lovinského', 'Valašská', 'Patrónka', 'ŽST Železná studienka'],
    ['Šulekova', 'Kozia', 'Hodžovo nám.', 'Kollárovo nám.', 'Mickiewiczova', 'Karadžičova', 'Kulíškova', 'Cvernovka',
     'Košická', 'Novohradská', 'BBCMliekárenská', 'Ružová dolina', 'BBC1 Plus-Miletičova', 'Novohradská',
     'Svätoplukova', 'Cvernovka', 'Kulíškova', 'Karadžičova', 'Americké nám.', 'Kollárovo nám.', 'Hodžovo nám.',
     'Kozia', 'Šulekova'],
    ['Nár. onkolog. ústav', 'Klenová', 'NÚSCH', 'Vlárska', 'Magurská', 'Bárdošova', 'Sokolská', 'Nám. Franza Liszta',
     'Karpatská', 'Račianske mýto', 'Trnavské mýto', 'Saleziáni', 'Trhovisko', 'Ružová dolina', 'Mliekárenská'],
    ['Mliekárenská', 'Ružová dolina', 'Trhovisko', 'Saleziáni', 'Trnavské mýto', 'Račianske mýto', 'Karpatská', 'SAV',
     'Sokolská', 'Stromová', 'Bárdošova', 'Magurská', 'Vlárska', 'NÚSCH', 'Klenová', 'Nár. onkolog. ústav'],
    ['Hlavná stanica', 'Nám. Franza Liszta', 'Karpatská', 'Račianske mýto', 'Krížna', 'Šoltésovej',
     'Autobusová stanica', 'Twin City', 'Nové SND'],
    ['Nové SND', 'Twin City', 'Autobusová stanica', 'Mlynské nivy', 'Šoltésovej', 'Krížna', 'Račianske mýto',
     'Karpatská', 'Hlavná stanica'],
    ['ŽST Železná studienka', 'Patrónka', 'Pri Suchom mlyne', 'Nemocnica Kramáre', 'Vlárska', 'Klenová',
     'Nár. onkolog. ústav'],
    ['Nár. onkolog. ústav', 'Klenová', 'Vlárska', 'Nemocnica Kramáre', 'Pri Suchom mlyne', 'Patrónka',
     'ŽST Železná studienka'],
    ['ŽST Železná studienka', 'Patrónka', 'Pri Suchom mlyne', 'Nemocnica Kramáre', 'Magurská', 'Bárdošova', 'Sokolská',
     'SAV', 'Hodžovo nám.', 'Kollárovo nám.', 'Špitálska', 'Ul. Cintorín Vrakuňa', 'Prievoz-most', 'Strojnícka',
     'Radničné nám.', 'Kaštieľska', 'MiÚ Ružinov', 'Hraničná-OC Retro', 'Pažítková', 'Prievozská',
     'BBC1 Plus-Miletičova', 'Novohradská', 'Svätoplukova', 'Autobusová stanica', 'Cintorínska', 'Špitálska',
     'Kollárovo nám.', 'Hodžovo nám.', 'SAV', 'Sokolská', 'Stromová', 'Bárdošova', 'Magurská', 'Nemocnica Kramáre',
     'Pri Suchom mlyne', 'Patrónka', 'ŽST Železná studienka'],
    ['Opletalova', 'Paulinské', 'Panské', 'Bystrická', 'ŽST Dev. Nová Ves', 'Mlynská', 'Novoveská', 'Hradištná',
     'Milana Marečka', 'Štefana Králika', 'Vápenka', 'Krpáš', 'Kamenáče', 'Bory-rázcestie', 'Technické sklo', 'Agátová',
     'Pri kríži', 'OD Saratov', 'Drobného', 'Alexyho', 'Švantnerova', 'Damborského', 'Lipského', 'Húščavova',
     'Tesco Lamač', 'Pekníkova', 'Žatevná'],
    ['Žatevná', 'Pekníkova', 'Tesco Lamač', 'Húščavova', 'Lipského', 'Damborského', 'Švantnerova', 'Alexyho',
     'Drobného', 'OD Saratov', 'Pri kríži', 'Agátová', 'Technické sklo', 'Bory-rázcestie', 'Kamenáče', 'Krpáš',
     'Vápenka', 'Štefana Králika', 'Milana Marečka', 'Hradištná', 'Novoveská', 'Mlynská', 'ŽST Dev. Nová Ves',
     'Bystrická', 'Panské', 'Paulinské', 'Opletalova'],
    ['Autobusová stanica', 'Krížna', 'Račianske mýto', 'SAV', 'Patrónka', 'Mokrohájska', 'Bory Mall', 'Bory-rázcestie',
     'Štefana Králika', 'Milana Marečka', 'Hradištná', 'Na hriadkach', 'Novoveská', 'Mlynská', 'Kremencová',
     'Zamajerské', 'Jána Jonáša-VW'],
    ['Jána Jonáša-VW', 'Zamajerské', 'Kremencová', 'Mlynská', 'Novoveská', 'Na hriadkach', 'Hradištná',
     'Milana Marečka', 'Štefana Králika', 'Bory-rázcestie', 'Bory Mall', 'Mokrohájska', 'Patrónka',
     'Nám. Franza Liszta', 'Račianske mýto', 'Krížna', 'Autobusová stanica'],
    ['Lamač', 'Klanec', 'Studenohorská', 'Podháj', 'Bakošova', 'Vrančovičova', 'Hodonínska', 'ŽST Lamač', 'Bilíkova',
     'Alexyho', 'Drobného', 'OD Saratov', 'Pri kríži', 'Agátová', 'Bory-rázcestie', 'Veľkolúcky potok',
     'ČOV Dev. Nová Ves', 'Jána Jonáša', 'Jána Jonáša-VW', 'Zamajerské', 'Kremencová', 'Vápencová', 'Rakyta', 'Mláka'],
    ['Mláka', 'Rakyta', 'Vápencová', 'Kremencová', 'Zamajerské', 'Jána Jonáša-VW', 'Jána Jonáša', 'ČOV Dev. Nová Ves',
     'Veľkolúcky potok', 'Bory-rázcestie', 'Agátová', 'Pri kríži', 'OD Saratov', 'Drobného', 'Alexyho', 'Na vrátkach',
     'Lediny', 'Vrančovičova', 'Bakošova', 'Podháj', 'Studenohorská', 'Klanec', 'Lamač'],
    ['Volkswagen', 'Jána Jonáša', 'Jána Jonáša-VW'],
    ['Jána Jonáša-VW', 'Jána Jonáša', 'Volkswagen'],
    ['Autobusová stanica', 'Krížna', 'Račianske mýto', 'SAV', 'Patrónka', 'Bory Mall', 'Veľkolúcky potok', 'Volkswagen',
     'Jána Jonáša', 'Jána Jonáša-VW'],
    ['Volkswagen', 'Veľkolúcky potok', 'Bory Mall', 'Patrónka', 'Nám. Franza Liszta', 'Račianske mýto', 'Krížna',
     'Autobusová stanica'],
    ['Žatevná', 'Pekníkova', 'OD Saratov', 'Pri kríži', 'Volkswagen', 'Jána Jonáša', 'Jána Jonáša-VW'],
    ['Jána Jonáša-VW', 'Jána Jonáša', 'Volkswagen', 'Pri kríži', 'OD Saratov', 'Pekníkova', 'Žatevná'],
    ['Alexyho', 'Vendelínska', 'Tulipánová', 'Žatevná', 'Štepná', 'Cabanova II', 'Cabanova', 'Homolova', 'Pri kríži',
     'Pri kríži', 'OC Dubrawa'],
    ['OC Dubrawa', 'Pri kríži', 'Homolova', 'Cabanova', 'Tranovského II', 'Tranovského', 'Štepná', 'Žatevná',
     'Tulipánová', 'Vendelínska', 'Alexyho'],
    ['Nové SND', 'Malá scéna', 'Most SNP', 'Chatam Sófer', 'Park kultúry', 'Lafranconi', 'Botanická záhrada',
     'Vodárenské múzeum', 'Jurigrad', 'Sihoť-BVS', 'Kadlečík', 'Zlaté schody', 'Hájovňa', 'Pri záhradách',
     'Nový kameňolom', 'Starý kameňolom', 'Dolné koruny', 'Kremeľská', 'Slovanské nábrežie', 'Nám. sv. Cyrila a Metoda',
     'Štrbská', 'Devín', 'Morava', 'Waitov lom', 'Sandberg', 'Na hriadkach', 'Uhrovecká', 'Ivana Bukovčana', 'Na Grbe',
     'Novoveská', 'Mlynská', 'ŽST Dev. Nová Ves', 'Bystrická', 'Panské', 'Paulinské', 'Opletalova'],
    ['Opletalova', 'Paulinské', 'Panské', 'Bystrická', 'ŽST Dev. Nová Ves', 'Mlynská', 'Novoveská', 'Uhrovecká',
     'Na Grbe', 'Ivana Bukovčana', 'Na hriadkach', 'Sandberg', 'Waitov lom', 'Morava', 'Devín', 'Štrbská',
     'Nám. sv. Cyrila a Metoda', 'Slovanské nábrežie', 'Kremeľská', 'Dolné koruny', 'Starý kameňolom', 'Nový kameňolom',
     'Pri záhradách', 'Hájovňa', 'Zlaté schody', 'Kadlečík', 'Sihoť-BVS', 'Jurigrad', 'Vodárenské múzeum',
     'Botanická záhrada', 'Lafranconi', 'Park kultúry', 'Chatam Sófer', 'Most SNP', 'Malá scéna', 'Nové SND'],
    ['Most SNP', 'Chatam Sófer', 'Park kultúry', 'Lafranconi', 'Botanická záhrada', 'Vodárenské múzeum', 'Jurigrad',
     'Sihoť-BVS', 'Kadlečík', 'Zlaté schody', 'Hájovňa', 'Pri záhradách', 'Nový kameňolom', 'Starý kameňolom',
     'Dolné koruny', 'Kremeľská', 'Slovanské nábrežie', 'Nám. sv. Cyrila a Metoda', 'Štrbská', 'Hrad Devín'],
    ['Hrad Devín', 'Štrbská', 'Nám. sv. Cyrila a Metoda', 'Slovanské nábrežie', 'Kremeľská', 'Dolné koruny',
     'Starý kameňolom', 'Nový kameňolom', 'Pri záhradách', 'Hájovňa', 'Zlaté schody', 'Kadlečík', 'Sihoť-BVS',
     'Jurigrad', 'Vodárenské múzeum', 'Botanická záhrada', 'Lafranconi', 'Park kultúry', 'Chatam Sófer', 'Most SNP'],
    ['Lamač', 'Klanec', 'Studenohorská', 'Podháj', 'Bakošova', 'Vrančovičova', 'Pod násypom', 'Segnáre', 'Hodonínska',
     'ŽST Lamač', 'Pridánky', 'Mokrohájska', 'Patrónka', 'Pri Habánskom mlyne', 'Zoo', 'Lafranconi', 'Park kultúry',
     'Chatam Sófer', 'Most SNP'],
    ['Most SNP', 'Chatam Sófer', 'Park kultúry', 'Lafranconi', 'Zoo', 'Pri Habánskom mlyne', 'Patrónka', 'Mokrohájska',
     'Pridánky', 'Segnáre-nadchod', 'ŽST Lamač', 'Pod násypom', 'Segnáre', 'Lediny', 'Vrančovičova', 'Bakošova',
     'Podháj', 'Studenohorská', 'Klanec', 'Lamač'],
    ['Cintorín Slávičie údolie', 'Televízia', 'Zoo', 'Lafranconi', 'Park kultúry', 'Chatam Sófer', 'Zochova',
     'Kollárovo nám.', 'Blumentál', 'Račianske mýto', 'Trnavské mýto'],
    ['Trnavské mýto', 'Račianske mýto', 'Povraznícka', 'STU', 'Kollárovo nám.', 'Zochova', 'Chatam Sófer',
     'Park kultúry', 'Lafranconi', 'Zoo', 'Televízia', 'Cintorín Slávičie údolie'],
    ['Kuklovská', 'ZŠ Majerníkova', 'Matejkova', 'Tománkova', 'Hany Meličkovej', 'Pri podchode', 'Janotova', 'Molecova',
     'Botanická záhrada', 'Zoo', 'Pri Habánskom mlyne', 'Pri Suchom mlyne', 'Nemocnica Kramáre', 'Magurská',
     'Bárdošova', 'Sokolská', 'Hlavná stanica'],
    ['Hlavná stanica', 'SAV', 'Sokolská', 'Bárdošova', 'Magurská', 'Nemocnica Kramáre', 'Pri Suchom mlyne',
     'Pri Habánskom mlyne', 'Zoo', 'Botanická záhrada', 'Molecova', 'Janotova', 'Pri podchode', 'Hany Meličkovej',
     'Tománkova', 'Matejkova', 'ZŠ Majerníkova', 'Kuklovská'],
    ['Kuklovská', 'Kuklovská Dúbravská cesta', 'Polianky', 'Lipského', 'Harmincova', 'Borská', 'Borská', 'Šaštínska',
     'Sološnická', 'Kuklovská 44', 'Kuklovská 60', 'Kuklovská'],
    ['Most SNP', 'Lafranconi', 'Zoo', 'Pri Habánskom mlyne', 'Patrónka', 'Tesco Lamač', 'ŽST Lamač', 'Vrančovičova',
     'Lamač-Staré záhrady', 'Pri krematóriu', 'Podkerepušky', 'Dievčí hrádok', 'TV Markíza', 'Krče',
     'MiÚ Záh. Bystrica', 'Záhorská', 'Záhorská Bystrica', 'Záhorská', 'Krče', 'Pri Vápenickom potoku', 'Pri kaplnke',
     'Strmé vŕšky', 'Trstínska', 'Marianka', 'Nad Bednárovým', 'Marianka', 'Cesta do Stupavy', 'Marianka', 'námestie'],
    ['Marianka', 'námestie', 'Marianka', 'Cesta do Stupavy', 'Marianka', 'Nad Bednárovým', 'Trstínska', 'Strmé vŕšky',
     'Pri kaplnke', 'Pri Vápenickom potoku', 'MiÚ Záh. Bystrica', 'Záhorská Bystrica', 'Záhorská', 'Krče', 'TV Markíza',
     'Dievčí hrádok', 'Podkerepušky', 'Pri krematóriu', 'Lamač-Staré záhrady', 'Vrančovičova', 'ŽST Lamač', 'Patrónka',
     'Pri Habánskom mlyne', 'Zoo', 'Lafranconi', 'Most SNP'],
    ['Cintorín Slávičie údolie', 'Televízia', 'Zoo', 'Lafranconi', 'Park kultúry', 'Chatam Sófer', 'Zochova',
     'Kollárovo nám.', 'Blumentál', 'Račianske mýto', 'Trnavské mýto', 'Zimný štadión', 'Bajkalská', 'Sabinovská',
     'Trnavská', 'Trnavská-NAD', 'Martinský cintorín', 'Clementisova', 'Ivanská cesta', 'Súhvezdná'],
    ['Súhvezdná', 'Ivanská cesta', 'Clementisova', 'Martinský cintorín', 'Trnavská-NAD', 'Trnavská', 'Sabinovská',
     'Bajkalská', 'Zimný štadión', 'Trnavské mýto', 'Račianske mýto', 'Povraznícka', 'STU', 'Kollárovo nám.', 'Zochova',
     'Chatam Sófer', 'Park kultúry', 'Lafranconi', 'Zoo', 'Televízia', 'Cintorín Slávičie údolie'],
    ['Hlavná stanica', 'SAV', 'Sokolská', 'Hroboňova', 'Prokopa Veľkého', 'Vozovňa Hroboňova', 'Súbežná', 'Hauerland',
     'Slov. nár. archív', 'Šafranová', 'Prvosienková', 'Na hrebienku', 'Búdková'],
    ['Búdková', 'Na hrebienku', 'Prvosienková', 'Šafranová', 'Slov. nár. archív', 'Hauerland', 'Súbežná',
     'Vozovňa Hroboňova', 'Hroboňova', 'Sokolská', 'Hlavná stanica'],
    ['Patrónka', 'ŽST Železná studienka', 'Červený most P+R', 'Klepáč', 'Deviaty mlyn', 'Železná studnička', 'Bukva',
     'Drieňovské lúky', 'Lanovka', 'Kameňolom', 'Lesopark', 'Kačínska dolina', 'Kačín'],
    ['Kačín', 'Kačínska dolina', 'Lesopark', 'Kameňolom', 'Lanovka', 'Drieňovské lúky', 'Bukva', 'Železná studnička',
     'Deviaty mlyn', 'Klepáč', 'Červený most P+R', 'ŽST Železná studienka', 'Patrónka'],
    ['Koliba', 'Júlová', 'Na Revíne', 'Júnová', 'Višňová', 'L. Dérera', 'Guothova', 'Bárdošova', 'Stromová',
     'Cesta na Kamzík', 'Jaskový rad'],
    ['Koliba', 'Júlová', 'Na Revíne', 'Júnová', 'Višňová', 'L. Dérera', 'Guothova', 'Bárdošova', 'Rozvodná', 'Klenová',
     'Nár. onkolog. ústav'],
    ['Jaskový rad', 'Matúškova', 'Žabotova', 'Cesta na Kamzík', 'Stromová', 'Bárdošova', 'Višňová', 'L. Dérera',
     'Guothova', 'Júnová', 'Na Revíne', 'Júlová', 'Koliba'],
    ['Nár. onkolog. ústav', 'Klenová', 'Rozvodná', 'Bárdošova', 'Višňová', 'L. Dérera', 'Guothova', 'Júnová',
     'Na Revíne', 'Júlová', 'Koliba'],
    ['OD Slimák', 'Kukučínova', 'Hálkova', 'Polus City Center', 'ŽST Nové Mesto', 'Trnavská', 'Haburská',
     'Maximiliána Hella', 'Tomášikova', 'Herlianska-OC Retro', 'Nemocnica Ružinov', 'Slovanet', 'Trhovisko',
     'Dulovo nám.', 'Svätoplukova', 'Autobusová stanica', 'Twin City', 'Panorama City', 'Most Apollo', 'Aupark'],
    ['Aupark', 'Most SNP', 'Malá scéna', 'Twin City', 'Autobusová stanica', 'Svätoplukova', 'Cvernovka', 'Dulovo nám.',
     'Trhovisko', 'Slovanet', 'Nemocnica Ružinov', 'Herlianska-OC Retro', 'Tomášikova', 'Maximiliána Hella', 'VD Úsvit',
     'Haburská', 'Trnavská', 'ŽST Nové Mesto', 'Polus City Center', 'Hálkova', 'Kukučínova', 'OD Slimák'],
    ['Trnavské mýto', 'Tehelná', 'OD Slimák', 'Kukučínova', 'Hálkova', 'Polus City Center', 'Odborárska',
     'Staré ihrisko', 'Eu. vzdel. akadémia', 'Nobelova', 'Vozovňa Krasňany'],
    ['Vozovňa Krasňany', 'Nobelova', 'Eu. vzdel. akadémia', 'Staré ihrisko', 'Odborárska', 'Zátišie',
     'Polus City Center', 'Hálkova', 'Kukučínova', 'OD Slimák', 'Tehelná', 'Trnavské mýto'],
    ['Na pasekách', 'Východné', 'Lokomotívne depo I', 'Sklabinská', 'Pri Šajbách', 'Pastierska', 'Stolárska',
     'Čachtická', 'Závadská', 'Tbiliská'],
    ['Tbiliská', 'Závadská', 'Čachtická', 'Ihrisková', 'Pastierska', 'Pri Šajbách', 'Sklabinská', 'Lokomotívne depo I',
     'Východné', 'Na pasekách'],
    ['Trnavské mýto', 'Nová doba', 'Bajkalská', 'Sabinovská', 'Trnavská', 'Slovinská', 'Rádiová', 'Vozovňa Trnávka',
     'Shopping Park Soravia', 'Zlaté piesky', 'Kon-Rad', 'Vajnory-nadjazd', 'Pri starom letisku', 'Uhliská',
     'MiÚ Vajnory', 'Hospodárska', 'Vajnory', 'Vajnory-konečná'],
    ['Vajnory-konečná', 'Vajnory', 'Hospodárska', 'MiÚ Vajnory', 'Uhliská', 'Pri starom letisku', 'Vajnory-nadjazd',
     'Kon-Rad', 'Zlaté piesky', 'Shopping Park Soravia', 'Vozovňa Trnávka', 'Rádiová', 'Slovinská', 'Trnavská',
     'Sabinovská', 'Bajkalská', 'Zimný štadión', 'Trnavské mýto'],
    ['Sklabinská', 'Lokomotívne depo I', 'Východné', 'Na pasekách', 'Lokomotívne depo II', 'Športové letisko',
     'Pri starom letisku', 'Uhliská', 'Čierny chodník', 'Pračanská', 'ŽST Vajnory'],
    ['ŽST Vajnory', 'Pri mlyne', 'Pračanská', 'Uhliská', 'Pri starom letisku', 'Obchod Vajnory', 'Športové letisko',
     'Lokomotívne depo II', 'Na pasekách', 'Východné', 'Lokomotívne depo I', 'Sklabinská'],
    ['Studená', 'Studená-zastávka', 'Shopping Palace', 'Zlaté piesky', 'Kon-Rad', 'Vajnory-nadjazd',
     'Pri starom letisku', 'Športové letisko', 'Lokomotívne depo II', 'Na pasekách', 'Východné', 'Lokomotívne depo I',
     'Sklabinská', 'Pri Šajbách', 'Pastierska', 'Stolárska', 'Čachtická', 'MiÚ Rača', 'Nemecký kultúrny dom', 'Barónka',
     'Nám. A. Hlinku', 'Závadská', 'Tbiliská', 'Karpatské nám.', 'Púchovská', 'Záhumenice-Drevona', 'Zvončeková',
     'Potočná'],
    ['Potočná', 'Zvončeková', 'Záhumenice-Drevona', 'Púchovská', 'Karpatské nám.', 'Tbiliská', 'Závadská',
     'Nám. A. Hlinku', 'Barónka', 'Nemecký kultúrny dom', 'MiÚ Rača', 'Čachtická', 'Ihrisková', 'Pastierska',
     'Pri Šajbách', 'Sklabinská', 'Lokomotívne depo I', 'Východné', 'Na pasekách', 'Lokomotívne depo II',
     'Športové letisko', 'Pri starom letisku', 'Vajnory-nadjazd', 'Kon-Rad', 'Zlaté piesky', 'Studená-zastávka',
     'Studená'],
    ['Vozovňa Jurajov dvor', 'Jurajov dvor', 'Pri nadjazde', 'Mokraď', 'Žabí majer-záhrady', 'Žabí majer',
     'Pribylinská', 'Staviteľská', 'Stavivá'],
    ['Žabí majer', 'Žabí majer-záhrady', 'Mokraď', 'Pribylinská', 'Staviteľská', 'Stavivá', 'Kalné jazero',
     'Spádovisko I', 'Spádovisko II', 'Zlaté piesky', 'Shopping Palace', 'ZIPP', 'Stará Vajnorská', 'Pri nadjazde',
     'Jurajov dvor', 'Vozovňa Jurajov dvor'],
    ['Technická', 'Bočná', 'Rádiová', 'Rádiová', 'Vihorlatská', 'Mierová kolónia', 'Magnetová', 'Odborárska',
     'ŽST Nové Mesto'],
    ['ŽST Nové Mesto', 'Odborárska', 'Magnetová', 'Mierová kolónia', 'Vihorlatská', 'Rádiová', 'Rádiová', 'Bočná',
     'Technická'],
    ['Na pantoch', 'OU železničné', 'OU obchodné', 'Rybničná', 'Púchovská', 'Trávna-Drevona', 'Pekná cesta',
     'ŽST Vinohrady', 'Pionierska', 'Račianske mýto', 'Dvory', 'ŽST Petržalka', 'Jiráskova', 'Smolenická', 'Lúky II',
     'Budatínska', 'Lúčanka', 'Ľubovnianska', 'Nemocnica Antolská', 'Antolská'],
    ['Antolská', 'Nemocnica Antolská', 'Ľubovnianska', 'Lúčanka', 'Budatínska', 'Lúky II', 'Smolenická', 'Jiráskova',
     'ŽST Petržalka', 'Dvory', 'Račianske mýto', 'Pionierska', 'ŽST Vinohrady', 'Pekná cesta', 'Trávna-Drevona',
     'Púchovská', 'Rybničná', 'OU obchodné', 'OU železničné', 'Na pantoch'],
    ['Letisko', 'Fatruny', 'Pestovateľská', 'Avion-IKEA', 'Avion Shopping Park', 'Galvaniho', 'Big Media-Slowackého',
     'Clementisova', 'Martinský cintorín', 'Trnavská-NAD', 'Trnavská', 'Sabinovská', 'Bajkalská', 'Zimný štadión',
     'Trnavské mýto', 'Račianske mýto', 'Karpatská', 'Hlavná stanica'],
    ['Hlavná stanica', 'Nám. Franza Liszta', 'Karpatská', 'Račianske mýto', 'Trnavské mýto', 'Zimný štadión',
     'Bajkalská', 'Sabinovská', 'Trnavská', 'Trnavská-NAD', 'Martinský cintorín', 'Clementisova',
     'Big Media-Slowackého', 'Avion Shopping Park', 'Avion-IKEA', 'Fatruny', 'Cesta na letisko', 'Letisko'],
    ['Avion Shopping Park', 'Galvaniho', 'Stará Ivanská', 'Vozovňa Trnávka', 'Rádiová', 'Slovinská', 'Trnavská',
     'Bajkalská', 'Zimný štadión', 'Trnavské mýto', 'Račianske mýto', 'SAV', 'Hroboňova', 'Patrónka', 'Tesco Lamač',
     'ŽST Lamač', 'Vrančovičova', 'Bakošova', 'Podháj', 'Studenohorská', 'Klanec', 'Lamač'],
    ['Lamač', 'Klanec', 'Studenohorská', 'Podháj', 'Bakošova', 'Vrančovičova', 'ŽST Lamač', 'Tesco Lamač', 'Patrónka',
     'Hroboňova', 'Nám. Franza Liszta', 'Račianske mýto', 'Trnavské mýto', 'Zimný štadión', 'Bajkalská', 'Trnavská',
     'Slovinská', 'Rádiová', 'Vozovňa Trnávka', 'Stará Ivanská', 'Avion Shopping Park', 'Avion Shopping Park'],
    ['Tbiliská', 'Závadská', 'Čachtická', 'Trávna-Drevona', 'Púchovská', 'Na pantoch', 'OU železničné', 'OU obchodné',
     'Rybničná', 'Šprinclov majer', 'Vojenský útvar', 'Koniarkova', 'Osloboditeľská', 'Uhliská', 'Pri starom letisku',
     'Vajnory-nadjazd', 'Kon-Rad', 'Zlaté piesky', 'Shopping Palace', 'ZIPP', 'Stará Vajnorská', 'Jurajov dvor',
     'Vozovňa Trnávka', 'Rádiová', 'Bulharská', 'Pri zvonici', 'Stará Ivanská', 'Avion Shopping Park', 'Ríbezľová',
     'Cintorín Vrakuňa', 'Slovnaftská', 'Podzáhradná', 'Hronská', 'Dudvážska', 'Čiližská'],
    ['Čiližská', 'Žitavská', 'Dudvážska', 'Hronská', 'Podzáhradná', 'Slovnaftská', 'Cintorín Vrakuňa', 'Ríbezľová',
     'Galvaniho', 'Stará Ivanská', 'Pri zvonici', 'Bulharská', 'Rádiová', 'Vozovňa Trnávka', 'Jurajov dvor',
     'Stará Vajnorská', 'ZIPP', 'Shopping Palace', 'Zlaté piesky', 'Tuhovská', 'Vajnory-nadjazd', 'Pri starom letisku',
     'Uhliská', 'Osloboditeľská', 'Koniarkova', 'Vojenský útvar', 'Šprinclov majer', 'Rybničná', 'Na pantoch',
     'OU železničné', 'OU obchodné', 'Vajnorský potok', 'Púchovská', 'Trávna-Drevona', 'Čachtická', 'Závadská',
     'Tbiliská'],
    ['Trhovisko', 'Slovanet', 'Drieňová', 'Bratislavská župa', 'Solivarská', 'Maximiliána Hella', 'DK Ružinov',
     'Nevädzová-OC Retro', 'Mierová', 'Krásna', 'Syslia', 'ŽST ÚNS', 'Domkárska'],
    ['Domkárska', 'ŽST ÚNS', 'Syslia', 'Krásna', 'Mierová', 'Nevädzová-OC Retro', 'DK Ružinov', 'Maximiliána Hella',
     'Solivarská', 'Bratislavská župa', 'Drieňová', 'Mliekárenská', 'Ružová dolina', 'Trhovisko'],
    ['Astronomická', 'Astronomická', 'Súhvezdná', 'Váhostav', 'Vrakuňa-záhrady', 'Majerská', 'Šípová', 'Železničná',
     'Čiližská', 'Žitavská', 'Dudvážska', 'Hronská', 'Bodrocká', 'Korytnická', 'Nákupná', 'Učiteľská',
     'MiÚ P. Biskupice', 'Devätinová', 'Vinohradnícka'],
    ['Vinohradnícka', 'Devätinová', 'MiÚ P. Biskupice', 'Nákupná', 'Korytnická', 'Bodrocká', 'Hronská', 'Dudvážska',
     'Čiližská', 'Železničná', 'Šípová', 'Majerská', 'Vrakuňa-záhrady', 'Váhostav', 'Astronomická'],
    ['Holíčska', 'Smolenická', 'Švabinského', 'Markova', 'Romanova', 'Hrobákova', 'Starohájska', 'Lachova', 'Šustekova',
     'Bulíkova', 'Ekonomická univerzita', 'Most Apollo', 'Prístavná', 'Košická', 'Dulovo nám.', 'Trhovisko',
     'Saleziáni', 'Krížna', 'Trnavské mýto'],
    ['Trnavské mýto', 'Saleziáni', 'Trhovisko', 'Dulovo nám.', 'Košická', 'Most Apollo', 'Ekonomická univerzita',
     'Bulíkova', 'Šustekova', 'Lachova', 'Starohájska', 'Hrobákova', 'Romanova', 'Markova', 'Švabinského', 'Smolenická',
     'Holíčska'],
    ['Avion Shopping Park', 'Avion Shopping Park', 'Avion-IKEA', 'Fatruny', 'Pharos'],
    ['Pharos', 'Pharos', 'Fatruny', 'Pestovateľská', 'Avion-IKEA', 'Avion Shopping Park'],
    ['Most SNP', 'Malá scéna', 'Twin City', 'Autobusová stanica', 'Košická', 'Novohradská', 'BBCŽST P. Biskupice',
     'Petőfiho', 'Učiteľská', 'MiÚ P. Biskupice', 'Nemocnica P. Biskupice', 'Šikmá', 'Slovnaftská', 'Ulica svornosti',
     'Závodná', 'Refinery Gallery', 'Vlčie hrdlo', 'Čierny les', 'Terminál', 'Pálenisko', 'Lúčna', 'Prístavný most',
     'Prievozská', 'BBC1 Plus-Miletičova', 'Novohradská', 'Svätoplukova', 'Autobusová stanica', 'Twin City',
     'Malá scéna', 'Most SNP'],
    ['Hlavná stanica', 'Nám. Franza Liszta', 'Karpatská', 'Račianske mýto', 'Trnavské mýto', 'Zimný štadión',
     'Bajkalská', 'Drieňová', 'Mliekárenská', 'Prístavný most', 'Lúčna', 'Pálenisko', 'Terminál', 'Čierny les',
     'Vlčie hrdlo'],
    ['Vlčie hrdlo', 'Čierny les', 'Terminál', 'Pálenisko', 'Lúčna', 'Prístavný most', 'Mliekárenská', 'Drieňová',
     'Bajkalská', 'Zimný štadión', 'Trnavské mýto', 'Račianske mýto', 'Karpatská', 'Hlavná stanica'],
    ['Čiližská', 'Žitavská', 'Dudvážska', 'Hronská', 'Komárovská', 'Priekopnícka', 'Cintorín Vrakuňa', 'Ondrejovova',
     'Brodná', 'Nevädzová-OC Retro', 'Herlianska-OC Retro', 'Nemocnica Ružinov', 'Bajkalská', 'Nová doba', 'Pionierska',
     'Mladá garda', 'ŽST Vinohrady', 'Hubeného', 'Kadnárova'],
    ['Kadnárova', 'Hubeného', 'ŽST Vinohrady', 'Mladá garda', 'Pionierska', 'Nová doba', 'Bajkalská',
     'Nemocnica Ružinov', 'Herlianska-OC Retro', 'Nevädzová-OC Retro', 'Brodná', 'Ondrejovova', 'Cintorín Vrakuňa',
     'Priekopnícka', 'Komárovská', 'Hronská', 'Dudvážska', 'Čiližská'],
    ['Spaľovňa', 'ČOV Vlčie hrdlo', 'Vodostav', 'Micherov majer', 'Vlčie hrdlo-záhrady', 'Povodie Dunaja', 'Lodenica',
     'Vlčie hrdlo-sídlisko', 'Vlčie hrdlo'],
    ['Vlčie hrdlo', 'Vlčie hrdlo-sídlisko', 'Lodenica', 'Povodie Dunaja', 'Vlčie hrdlo-záhrady', 'Micherov majer',
     'ČOV Vlčie hrdlo', 'Spaľovňa'],
    ['Čiližská', 'Žitavská', 'Dudvážska', 'Hronská', 'Toryská', 'Stavbárska', 'Estónska', 'Šíravská', 'Šípová',
     'Majerská', 'Vrakuňa-záhrady', 'Astronomická', 'Súmračná', 'Maximiliána Hella', 'Solivarská', 'Bratislavská župa',
     'Bajkalská', 'Zimný štadión', 'Trnavské mýto', 'Krížna', 'Šoltésovej', 'Mlynské nivy', 'Twin City', 'Nové SND'],
    ['Nové SND', 'Malá scéna', 'Twin City', 'Mlynské nivy', 'Šoltésovej', 'Krížna', 'Trnavské mýto', 'Zimný štadión',
     'Bajkalská', 'Bratislavská župa', 'Solivarská', 'Maximiliána Hella', 'Súmračná', 'Astronomická', 'Vrakuňa-záhrady',
     'Majerská', 'Šípová', 'Šíravská', 'Estónska', 'Stavbárska', 'Toryská', 'Hronská', 'Dudvážska', 'Čiližská'],
    ['Čiližská', 'Železničná', 'Podunajská', 'Komárovská', 'Toryská', 'Hronská', 'Dudvážska', 'ŽST P. Biskupice',
     'Petőfiho', 'Učiteľská', 'MiÚ P. Biskupice', 'Lieskovská cesta', 'PD P. Biskupice', 'Jánske hony',
     'Plniareň plynu', 'Lieskovec', 'Ketelec', 'Topoľové'],
    ['Topoľové', 'Ketelec', 'Lieskovec', 'Plniareň plynu', 'Jánske hony', 'PD P. Biskupice', 'Lieskovská cesta',
     'MiÚ P. Biskupice', 'Ul. 8. mája', 'ŽST P. Biskupice', 'Dudvážska', 'Hronská', 'Toryská', 'Komárovská',
     'Podunajská', 'Železničná', 'Čiližská'],
    ['Kollárovo nám.', 'Zochova', 'Einsteinova', 'Kremnická', 'Záporožská', 'ŽST Petržalka', 'Údernícka-Kúpalisko',
     'Dargovská', 'Cintorín Petržalka', 'Kopčianska-stred', 'Kopčany-sídlisko', 'Kopčianska', 'Kopčany'],
    ['Kopčany', 'Kopčianska', 'Kopčany-sídlisko', 'Kopčianska-stred', 'Cintorín Petržalka', 'Dargovská',
     'Údernícka-Kúpalisko', 'ŽST Petržalka', 'Záporožská', 'Kremnická', 'Einsteinova', 'Aupark', 'Zochova',
     'Kollárovo nám.'],
    ['Technopol', 'Bradáčova', 'Romanova', 'Hrobákova', 'Nám. hraničiarov', 'Jungmannova', 'Hálova', 'Dvory', 'Aupark',
     'Zochova', 'Hodžovo nám.', 'SAV', 'Sokolská', 'Hroboňova', 'Dubová', 'Patrónka', 'Mokrohájska', 'Húščavova',
     'Lipského', 'Damborského', 'Švantnerova', 'Alexyho', 'Drobného', 'Pekníkova', 'Žatevná', 'Štepná', 'Homolova',
     'Pri kríži'],
    ['Pri kríži', 'Homolova', 'Štepná', 'Žatevná', 'Pekníkova', 'Drobného', 'Alexyho', 'Švantnerova', 'Damborského',
     'Lipského', 'Húščavova', 'Mokrohájska', 'Patrónka', 'Dubová', 'Hroboňova', 'Sokolská', 'SAV', 'Hodžovo nám.',
     'Zochova', 'Aupark', 'Dvory', 'Hálova', 'Jungmannova', 'Nám. hraničiarov', 'Hrobákova', 'Romanova', 'Bradáčova',
     'Technopol'],
    ['Ovsište', 'Ovsištské nám.', 'Bulíkova', 'Šustekova', 'Bosákova', 'Mlynarovičova', 'Farského', 'Jungmannova',
     'Hálova', 'Dvory', 'Aupark', 'Zochova', 'Hodžovo nám.', 'SAV', 'Sokolská', 'Hroboňova', 'Dubová', 'Patrónka',
     'Mokrohájska', 'Húščavova', 'Lipského', 'Damborského', 'Švantnerova', 'Alexyho', 'Drobného', 'OD Saratov',
     'Pri kríži'],
    ['Pri kríži', 'OD Saratov', 'Drobného', 'Alexyho', 'Švantnerova', 'Damborského', 'Lipského', 'Húščavova',
     'Mokrohájska', 'Patrónka', 'Dubová', 'Hroboňova', 'Sokolská', 'SAV', 'Hodžovo nám.', 'Zochova', 'Aupark', 'Dvory',
     'Hálova', 'Jungmannova', 'Farského', 'Mlynarovičova', 'Šustekova', 'Bulíkova', 'Ovsištské nám.', 'Ovsište'],
    ['Astronomická', 'Astronomická', 'Súhvezdná', 'Váhostav', 'Vrakuňa-záhrady', 'Majerská', 'Šípová', 'Šíravská',
     'Estónska', 'Stavbárska', 'Toryská', 'Podzáhradná', 'Slovnaftská', 'Ulica svornosti', 'Závodná',
     'Refinery Gallery', 'Vlčie hrdlo', 'Čierny les', 'Terminál', 'Pálenisko', 'Lúčna', 'Prístav', 'Plynárenská',
     'Most Apollo', 'Ekonomická univerzita', 'Ovsištské nám.', 'Ovsište', 'Betliarska', 'Vozovňa Petržalka'],
    ['Ovsište', 'Ovsištské nám.', 'Ekonomická univerzita', 'Most Apollo', 'Prístavná', 'Plynárenská', 'Prístav',
     'Lúčna', 'Pálenisko', 'Terminál', 'Čierny les', 'Vlčie hrdlo', 'Refinery Gallery', 'Závodná', 'Ulica svornosti',
     'Slovnaftská', 'Podzáhradná', 'Toryská', 'Stavbárska', 'Estónska', 'Šíravská', 'Šípová', 'Majerská',
     'Vrakuňa-záhrady', 'Váhostav', 'Astronomická'],
    ['Most SNP', 'Einsteinova', 'Kremnická', 'Záporožská', 'Gercenova', 'Hálova', 'Jungmannova', 'Nám. hraničiarov',
     'Lachova', 'Šustekova', 'Bulíkova', 'Ekonomická univerzita', 'Most Apollo', 'Prístavná', 'Panorama City',
     'Twin City', 'Autobusová stanica'],
    ['Autobusová stanica', 'Twin City', 'Panorama City', 'Most Apollo', 'Ekonomická univerzita', 'Bulíkova',
     'Šustekova', 'Lachova', 'Nám. hraničiarov', 'Jungmannova', 'Hálova', 'Gercenova', 'Záporožská', 'Kremnická',
     'Einsteinova', 'Aupark', 'Most SNP'],
    ['Nové SND', 'Panorama City', 'Most Apollo', 'Ekonomická univerzita', 'Žehrianska', 'Slnečnice', 'Jarovce-záhrady',
     'Strelnica', 'Píla', 'Jarovce', 'Sady', 'Kovácsova', 'Vývojová', 'Gerulata', 'Kaštieľ Rusovce', 'ŽST Rusovce',
     'Gaštanová aleja', 'Pieskový hon', 'Čunovské jazerá', 'Schengenská', 'Čunovo-záhrady', 'Čunovo-priehrada',
     'Areál vodných športov', 'Danubiana'],
    ['Danubiana', 'Areál vodných športov', 'Čunovo-priehrada', 'Čunovo-záhrady', 'Schengenská', 'Čunovské jazerá',
     'Pieskový hon', 'Gaštanová aleja', 'ŽST Rusovce', 'Kaštieľ Rusovce', 'Gerulata', 'Vývojová', 'Kovácsova', 'Sady',
     'Jarovce', 'Píla', 'Strelnica', 'Jarovce-záhrady', 'Slnečnice', 'Jasovská', 'Žehrianska', 'Ekonomická univerzita',
     'Most Apollo', 'Nové SND'],
    ['Most SNP', 'Aupark', 'Dvory', 'ŽST Petržalka', 'Kolmá', 'Nákupná zóna Lúky', 'Jasovská', 'Slnečnice',
     'Jarovce-záhrady', 'Strelnica', 'Píla', 'Jarovce', 'Sady', 'Kovácsova', 'Vývojová', 'Gerulata', 'Kaštieľ Rusovce',
     'ŽST Rusovce', 'Gaštanová aleja', 'Pieskový hon', 'Čunovské jazerá', 'MiÚ Čunovo', 'Čunovo-námestie', 'Čunovo'],
    ['Čunovo', 'Čunovo-námestie', 'MiÚ Čunovo', 'Čunovské jazerá', 'Pieskový hon', 'Gaštanová aleja', 'Kaštieľ Rusovce',
     'Gerulata', 'Vývojová', 'Kovácsova', 'Sady', 'Jarovce', 'Píla', 'Strelnica', 'Jarovce-záhrady', 'Slnečnice',
     'Jasovská', 'Nákupná zóna Lúky', 'Kolmá', 'ŽST Petržalka', 'Dvory', 'Aupark', 'Most SNP'],
    ['Opletalova', 'Paulinské', 'Panské', 'ŽST Dev. Nová Ves', 'Jána Jonáša-VW', 'Jána Jonáša', 'Volkswagen',
     'Veľkolúcky potok', 'Bory-rázcestie', 'Bory Mall', 'Lamač-Staré záhrady', 'Vrančovičova', 'ŽST Lamač',
     'Mokrohájska', 'Patrónka', 'Pri Habánskom mlyne', 'Zoo', 'Einsteinova', 'Dvory', 'Hálova', 'Jungmannova',
     'Nám. hraničiarov', 'Hrobákova', 'Romanova', 'Bradáčova', 'Technopol', 'Topoľčianska', 'Šintavská', 'Strečnianska',
     'Lúčanka', 'Ľubovnianska', 'Bzovícka', 'Betliarska', 'Vozovňa Petržalka'],
    ['Vozovňa Petržalka', 'Betliarska', 'Bzovícka', 'Ľubovnianska', 'Lúčanka', 'Strečnianska', 'Šintavská',
     'Topoľčianska', 'Technopol', 'Bradáčova', 'Romanova', 'Hrobákova', 'Nám. hraničiarov', 'Jungmannova', 'Hálova',
     'Dvory', 'Einsteinova', 'Zoo', 'Pri Habánskom mlyne', 'Patrónka', 'Mokrohájska', 'ŽST Lamač', 'Vrančovičova',
     'Lamač-Staré záhrady', 'Bory Mall', 'Bory-rázcestie', 'Veľkolúcky potok', 'Volkswagen', 'Jána Jonáša',
     'Jána Jonáša-VW', 'ŽST Dev. Nová Ves', 'Panské', 'Paulinské', 'Opletalova'],
    ['Hlavná stanica', 'SAV', 'Hodžovo nám.', 'Zochova', 'Aupark', 'Dvory', 'Rusovská cesta', 'ŽST Petržalka',
     'VŠ Manažmentu', 'Jiráskova', 'Smolenická', 'Lúky II', 'ZŠ Budatínska', 'Budatínska', 'Lúky V', 'Vyšehradská',
     'Ľubovnianska', 'Bzovícka', 'Betliarska', 'Vozovňa Petržalka'],
    ['Vozovňa Petržalka', 'Betliarska', 'Bzovícka', 'Ľubovnianska', 'Vyšehradská', 'Lúky V', 'Budatínska',
     'ZŠ Budatínska', 'Lúky II', 'Smolenická', 'Jiráskova', 'VŠ Manažmentu', 'ŽST Petržalka', 'Rusovská cesta', 'Dvory',
     'Aupark', 'Zochova', 'Hodžovo nám.', 'SAV', 'Hlavná stanica'],
    ['Holíčska', 'Smolenická', 'Jiráskova', 'VŠ Manažmentu', 'ŽST Petržalka', 'Rusovská cesta', 'Dvory', 'Aupark',
     'Zochova', 'Kollárovo nám.', 'Blumentál'],
    ['Blumentál', 'STU', 'Kollárovo nám.', 'Zochova', 'Aupark', 'Dvory', 'Rusovská cesta', 'ŽST Petržalka',
     'VŠ Manažmentu', 'Jiráskova', 'Smolenická', 'Holíčska'],
    ['Muchovo nám.', 'Farského', 'Nám. hraničiarov', 'Hrobákova', 'Romanova', 'Bradáčova', 'Technopol', 'Topoľčianska',
     'Šintavská', 'Strečnianska', 'Lúčanka', 'Vyšehradská'],
    ['Vyšehradská', 'Lúčanka', 'Strečnianska', 'Šintavská', 'Topoľčianska', 'Technopol', 'Bradáčova', 'Romanova',
     'Hrobákova', 'Nám. hraničiarov', 'Farského', 'Muchovo nám.'],
    ['Prokofievova', 'Markova', 'Romanova', 'Hrobákova', 'Starohájska', 'Lachova', 'Bosákova', 'Prístavný most',
     'Prievozská', 'Hraničná-OC Retro', 'Nevädzová-OC Retro', 'DK Ružinov', 'Maximiliána Hella', 'Haburská',
     'Slovinská', 'Rádiová', 'Vozovňa Trnávka', 'Stará Ivanská', 'Avion Shopping Park', 'Avion-IKEA', 'Fatruny',
     'Cesta na letisko', 'Letisko'],
    ['Letisko', 'Fatruny', 'Pestovateľská', 'Avion-IKEA', 'Avion Shopping Park', 'Galvaniho', 'Stará Ivanská',
     'Vozovňa Trnávka', 'Rádiová', 'Slovinská', 'Trnavská', 'Haburská', 'Maximiliána Hella', 'DK Ružinov',
     'Nevädzová-OC Retro', 'Gagarinova-Rádio Europa 2', 'Hraničná-OC Retro', 'Prievozská', 'Prístavný most', 'Bosákova',
     'Lachova', 'Starohájska', 'Hrobákova', 'Romanova', 'Markova', 'Prokofievova'],
    ['Jasovská', 'Žehrianska', 'Bzovícka', 'Ľubovnianska', 'Lúčanka', 'Znievska', 'Budatínska', 'ZŠ Budatínska',
     'Lúky II', 'Smolenická', 'Tupolevova', 'Technopol', 'Malý Draždiak', 'Starý háj', 'Ovsištské nám.',
     'Ekonomická univerzita', 'Prístavný most', 'Mliekárenská', 'Bajkalská', 'Nová doba', 'Polus City Center',
     'Polus City Center', 'Hálkova', 'Kukučínova', 'OD Slimák'],
    ['OD Slimák', 'Nová doba', 'Bajkalská', 'Mliekárenská', 'Prístavný most', 'Ekonomická univerzita', 'Ovsištské nám.',
     'Starý háj', 'Malý Draždiak', 'Technopol', 'Tupolevova', 'Smolenická', 'Lúky II', 'ZŠ Budatínska', 'Budatínska',
     'Znievska', 'Lúčanka', 'Ľubovnianska', 'Bzovícka', 'Žehrianska', 'Jasovská'],
    ['Ovsište', 'Ovsištské nám.', 'Bulíkova', 'Šustekova', 'Bosákova', 'Mlynarovičova', 'Farského', 'Jungmannova',
     'Hálova', 'ŽST Petržalka', 'Kopčianska-stred', 'Kopčany-sídlisko', 'Jiráskova', 'Švabinského', 'Markova',
     'Romanova', 'Bradáčova', 'Technopol', 'Topoľčianska', 'Šintavská', 'Holíčska', 'Lúky II', 'ZŠ Budatínska',
     'Budatínska', 'Znievska', 'Lúčanka', 'Ľubovnianska', 'Bzovícka', 'Betliarska', 'Vozovňa Petržalka',
     'Nemocnica Antolská', 'Antolská'],
    ['Antolská', 'Nemocnica Antolská', 'Ľubovnianska', 'Lúčanka', 'Znievska', 'Budatínska', 'ZŠ Budatínska', 'Lúky II',
     'Holíčska', 'Šintavská', 'Topoľčianska', 'Technopol', 'Bradáčova', 'Romanova', 'Markova', 'Švabinského',
     'Jiráskova', 'Kopčany-sídlisko', 'Kopčianska-stred', 'ŽST Petržalka', 'Hálova', 'Jungmannova', 'Farského',
     'Mlynarovičova', 'Šustekova', 'Bulíkova', 'Ovsištské nám.', 'Ovsište'],
    ['Žatevná', 'Pekníkova', 'OD Saratov', 'Pri kríži', 'Agátová', 'Bory Mall', 'Lamač-Staré záhrady', 'Bakošova',
     'Podháj', 'Studenohorská', 'Klanec', 'Lamač'],
    ['Lamač', 'Klanec', 'Studenohorská', 'Podháj', 'Bakošova', 'Lamač-Staré záhrady', 'Bory Mall', 'Agátová',
     'Pri kríži', 'OD Saratov', 'Pekníkova', 'Žatevná'],
    ['Patrónka', 'Kaufland', 'Patrónka', 'Mokrohájska', 'Tesco Lamač', 'Pod Zečákom', 'Segnáre', 'Lediny',
     'Vrančovičova', 'Lamač', 'Klanec', 'Studenohorská', 'Podháj', 'Bakošova', 'Lamač-Staré záhrady'],
    ['Lamač-Staré záhrady', 'Bakošova', 'Podháj', 'Studenohorská', 'Klanec', 'Lamač', 'Vrančovičova', 'Pod násypom',
     'Segnáre', 'Pod Zečákom', 'Tesco Lamač', 'Mokrohájska', 'Patrónka', 'Patrónka', 'Kaufland'],
    ['Hlavná stanica', 'Zochova', 'Lafranconi', 'Cintorín Slávičie údolie'],
    ['Kuklovská', 'ZŠ Majerníkova', 'Matejkova', 'Tománkova', 'Hany Meličkovej', 'Pri podchode', 'Janotova',
     'Lafranconi', 'Most SNP', 'Malá scéna', 'Nové SND'],
    ['Nové SND', 'Malá scéna', 'Most SNP', 'Lafranconi', 'Molecova', 'Janotova', 'Pri podchode', 'Hany Meličkovej',
     'Tománkova', 'Matejkova', 'ZŠ Majerníkova', 'Kuklovská'],
    ['Cintorín Slávičie údolie', 'Internáty B', 'Konvalinková', 'Vretenová', 'Na Sitine', 'Nad vinicami',
     'Nad internátmi', 'Grunty', 'Panoráma', 'Molecova'],
    ['Molecova', 'Jurigovo nám.', 'Hájnická', 'Panoráma', 'Grunty', 'Nad internátmi', 'Nad vinicami', 'Na Sitine',
     'Vretenová', 'Konvalinková', 'Internáty B', 'Cintorín Slávičie údolie'],
    ['Búdková', 'Stará vinárska', 'Slavín', 'Kalvária', 'Kalvária', 'Havlíčkova', 'Mišíkova', 'Donovalova', 'Šulekova',
     'Kozia', 'Hodžovo nám.'],
    ['Hodžovo nám.', 'Zochova', 'Šulekova', 'Donovalova', 'Mišíkova', 'Havlíčkova', 'Kalvária', 'Kalvária',
     'Havlíčkova', 'Slavín', 'Stará vinárska', 'Búdková'],
    ['OD Slimák', 'Tehelná', 'Pionierska', 'Sliačska', 'Briežky', 'Krahulčia', 'Lopenícka'],
    ['Lopenícka', 'Sliačska', 'Pionierska', 'Tehelná', 'Kukučínova', 'OD Slimák'],
    ['Shopping Palace', 'Zlaté piesky', 'Pri mlyne', 'Pračanská', 'MiÚ Vajnory', 'Hospodárska', 'Vajnory',
     'Vajnory-konečná'],
    ['Vajnory-konečná', 'Vajnory', 'Hospodárska', 'MiÚ Vajnory', 'Pračanská', 'Pri mlyne', 'Zlaté piesky',
     'Shopping Palace'],
    ['Ekonomická univerzita', 'Zochova', 'Hodžovo nám.', 'SAV', 'Prokopa Veľkého'],
    ['Hroboňova', 'SAV', 'Hodžovo nám.', 'Zochova', 'Ekonomická univerzita'],
    ['Most SNP', 'Aupark', 'Dvory', 'ŽST Petržalka', 'Kolmá', 'Nákupná zóna Lúky', 'Jasovská', 'Slnečnice',
     'Jarovce-záhrady', 'Strelnica', 'Píla', 'Jarovce', 'Sady', 'Kovácsova', 'Vývojová', 'Gerulata', 'Kaštieľ Rusovce',
     'ŽST Rusovce'],
    ['ŽST Rusovce', 'Kaštieľ Rusovce', 'Gerulata', 'Vývojová', 'Kovácsova', 'Sady', 'Jarovce', 'Píla', 'Strelnica',
     'Jarovce-záhrady', 'Slnečnice', 'Jasovská', 'Nákupná zóna Lúky', 'Kolmá', 'ŽST Petržalka', 'Dvory', 'Aupark',
     'Most SNP'],
    ['Tesco Lamač', 'Mokrohájska', 'Patrónka', 'Pri Habánskom mlyne', 'Zoo', 'Einsteinova', 'Dvory', 'Hálova',
     'Jungmannova', 'Nám. hraničiarov', 'Hrobákova', 'Romanova', 'Bradáčova', 'Technopol', 'Topoľčianska', 'Šintavská',
     'Strečnianska', 'Lúčanka', 'Ľubovnianska', 'Bzovícka', 'Betliarska', 'Vozovňa Petržalka'],
    ['Vozovňa Petržalka', 'Betliarska', 'Bzovícka', 'Ľubovnianska', 'Lúčanka', 'Strečnianska', 'Šintavská',
     'Topoľčianska', 'Technopol', 'Bradáčova', 'Romanova', 'Hrobákova', 'Nám. hraničiarov', 'Jungmannova', 'Hálova',
     'Dvory', 'Einsteinova', 'Zoo', 'Pri Habánskom mlyne', 'Patrónka', 'Mokrohájska', 'Tesco Lamač'],
    ['Prokofievova', 'Markova', 'Romanova', 'Hrobákova', 'Starohájska', 'Lachova', 'Bosákova', 'Prístavný most',
     'Prievozská', 'Hraničná-OC Retro', 'Nevädzová-OC Retro', 'DK Ružinov', 'Maximiliána Hella', 'Haburská', 'Trnavská',
     'ŽST Nové Mesto', 'Odborárska', 'Magnetová', 'Vozovňa Jurajov dvor'],
    ['Vozovňa Jurajov dvor', 'Magnetová', 'Odborárska', 'ŽST Nové Mesto', 'Trnavská', 'Haburská', 'Maximiliána Hella',
     'DK Ružinov', 'Nevädzová-OC Retro', 'Gagarinova-Rádio Europa 2', 'Hraničná-OC Retro', 'Prievozská',
     'Prístavný most', 'Bosákova', 'Lachova', 'Starohájska', 'Hrobákova', 'Romanova', 'Markova', 'Prokofievova'],
    ['Shopping Palace', 'Zlaté piesky', 'Pri mlyne', 'Pračanská', 'MiÚ Vajnory', 'Hospodárska', 'Vajnory',
     'Čierna Voda', 'Vajnorská', 'Čierna Voda', 'Čerešňová', 'Čierna Voda', 'Na pasienku', 'Čierna Voda',
     'Hornodvorská', 'Čierna Voda', 'Monar', 'Čierna Voda', 'Triangel', 'Chorvátsky Grob', 'Lúčna', 'Chorvátsky Grob',
     'Výhon', 'Chorvátsky Grob', 'námestie'],
    ['Chorvátsky Grob', 'námestie', 'Chorvátsky Grob', 'Výhon', 'Chorvátsky Grob', 'Lúčna', 'Čierna Voda', 'Triangel',
     'Čierna Voda', 'Monar', 'Čierna Voda', 'Hornodvorská', 'Čierna Voda', 'Na pasienku', 'Čierna Voda', 'Čerešňová',
     'Čierna Voda', 'Vajnorská', 'Vajnory', 'Hospodárska', 'MiÚ Vajnory', 'Pračanská', 'Pri mlyne', 'Zlaté piesky',
     'Shopping Palace'],
    ['ŽST Rusovce', 'Gaštanová aleja', 'Pieskový hon', 'Rajka', 'Benzinkút'],
    ['Rajka', 'Benzinkút', 'Rajka', 'Autóbuszforduló', 'Rajka', 'Szabadság tér', 'Rajka', 'Véradópark', 'Pieskový hon',
     'Gaštanová aleja', 'ŽST Rusovce'],
    ['Most SNP', 'Einsteinova', 'Wolfsthal', 'Bhf', 'Hauptstrasse Hainburg/Donau', 'Pfaffenbergweg', 'Hainburg/Donau',
     'Wiener Tor', 'Hainburg/Donau', 'Ungartor/B9', 'Hainburg/Donau', 'Pressburger Reichsstrasse', 'Wolfsthal', 'Bhf',
     'Hauptstrasse 40', 'Einsteinova', 'Aupark', 'Most SNP'],
    ['Hlavná stanica', 'SAV', 'Sokolská', 'Hroboňova', 'Dubová', 'Patrónka', 'Mokrohájska', 'Pridánky',
     'Segnáre-nadchod', 'ŽST Lamač', 'Bilíkova', 'Alexyho', 'Drobného', 'OD Saratov', 'Pri kríži', 'Agátová',
     'Bory-rázcestie', 'Kamenáče', 'Krpáš', 'Vápenka', 'Štefana Králika'],
    ['Štefana Králika', 'Milana Marečka', 'Hradištná', 'Uhrovecká', 'Novoveská', 'Mlynská', 'Kremencová', 'Zamajerské',
     'Jána Jonáša-VW', 'Jána Jonáša', 'ČOV Dev. Nová Ves', 'Veľkolúcky potok', 'Bory-rázcestie', 'Agátová', 'Pri kríži',
     'OD Saratov', 'Drobného', 'Alexyho', 'ŽST Lamač', 'Pridánky', 'Mokrohájska', 'Patrónka', 'Dubová', 'Hroboňova',
     'Sokolská', 'Hlavná stanica'],
    ['Hlavná stanica', 'SAV', 'Sokolská', 'Stromová', 'Bárdošova', 'Magurská', 'Nemocnica Kramáre', 'Pri Suchom mlyne',
     'Pri Habánskom mlyne', 'Zoo', 'Botanická záhrada', 'Vodárenské múzeum', 'Jurigrad', 'Sihoť-BVS', 'Kadlečík',
     'Zlaté schody', 'Hájovňa', 'Pri záhradách', 'Nový kameňolom', 'Starý kameňolom', 'Dolné koruny', 'Kremeľská',
     'Slovanské nábrežie', 'Nám. sv. Cyrila a Metoda', 'Štrbská', 'Hrad Devín'],
    ['Hrad Devín', 'Štrbská', 'Nám. sv. Cyrila a Metoda', 'Slovanské nábrežie', 'Kremeľská', 'Dolné koruny',
     'Starý kameňolom', 'Nový kameňolom', 'Pri záhradách', 'Hájovňa', 'Zlaté schody', 'Kadlečík', 'Sihoť-BVS',
     'Jurigrad', 'Vodárenské múzeum', 'Botanická záhrada', 'Zoo', 'Pri Habánskom mlyne', 'Pri Suchom mlyne',
     'Nemocnica Kramáre', 'Magurská', 'Bárdošova', 'Sokolská', 'Hlavná stanica'],
    ['Hlavná stanica', 'SAV', 'Hodžovo nám.', 'Zochova', 'Chatam Sófer', 'Park kultúry', 'Lafranconi', 'Zoo',
     'Televízia', 'Cintorín Slávičie údolie'],
    ['Cintorín Slávičie údolie', 'Televízia', 'Zoo', 'Lafranconi', 'Park kultúry', 'Chatam Sófer', 'Zochova',
     'Hodžovo nám.', 'SAV', 'Hlavná stanica'],
    ['Hlavná stanica', 'Nám. Franza Liszta', 'Karpatská', 'Račianske mýto', 'Krížna', 'Šoltésovej', 'Mlynské nivy',
     'Twin City', 'Malá scéna', 'Nám. Ľ. Štúra', 'Most SNP', 'Chatam Sófer', 'Park kultúry', 'Lafranconi',
     'Botanická záhrada', 'Molecova', 'Janotova', 'Pri podchode', 'Hany Meličkovej', 'Tománkova', 'Matejkova',
     'ZŠ Majerníkova', 'Kuklovská'],
    ['Kuklovská', 'ZŠ Majerníkova', 'Matejkova', 'Tománkova', 'Hany Meličkovej', 'Pri podchode', 'Janotova', 'Molecova',
     'Botanická záhrada', 'Lafranconi', 'Park kultúry', 'Chatam Sófer', 'Most SNP', 'Nám. Ľ. Štúra', 'Malá scéna',
     'Twin City', 'Mlynské nivy', 'Šoltésovej', 'Krížna', 'Račianske mýto', 'Karpatská', 'Nám. Franza Liszta',
     'Hlavná stanica'],
    ['Hlavná stanica', 'SAV', 'Hodžovo nám.', 'Zochova', 'Chatam Sófer', 'Park kultúry', 'Lafranconi',
     'Botanická záhrada', 'Molecova', 'Segnerova', 'Nad lúčkami', 'MiÚ Karlova Ves', 'Borská', 'Harmincova',
     'Damborského', 'Švantnerova', 'Alexyho', 'Drobného', 'Pekníkova', 'Žatevná', 'Štepná', 'Homolova', 'Pri kríži'],
    ['Pri kríži', 'Homolova', 'Štepná', 'Žatevná', 'Pekníkova', 'Drobného', 'Alexyho', 'Švantnerova', 'Damborského',
     'Harmincova', 'Borská', 'MiÚ Karlova Ves', 'Nad lúčkami', 'Segnerova', 'Molecova', 'Botanická záhrada',
     'Lafranconi', 'Park kultúry', 'Chatam Sófer', 'Zochova', 'Hodžovo nám.', 'SAV', 'Hlavná stanica'],
    ['Hlavná stanica', 'SAV', 'Sokolská', 'Hroboňova', 'Dubová', 'Patrónka', 'Mokrohájska', 'Tesco Lamač', 'Pridánky',
     'Segnáre-nadchod', 'ŽST Lamač', 'Lediny', 'Vrančovičova', 'Lamač', 'Klanec', 'Studenohorská', 'Podháj', 'Bakošova',
     'Lamač-Staré záhrady', 'Pri krematóriu', 'Podkerepušky', 'Dievčí hrádok', 'Krče', 'Záhorská', 'Záhorská Bystrica'],
    ['Záhorská Bystrica', 'Záhorská', 'Krče', 'Dievčí hrádok', 'Podkerepušky', 'Pri krematóriu', 'Lamač-Staré záhrady',
     'Bakošova', 'Podháj', 'Studenohorská', 'Klanec', 'Lamač', 'Vrančovičova', 'Hodonínska', 'ŽST Lamač', 'Pridánky',
     'Tesco Lamač', 'Mokrohájska', 'Patrónka', 'Dubová', 'Hroboňova', 'Sokolská', 'Hlavná stanica'],
    ['Hodžovo nám.', 'Nám. slobody', 'Štefanovičova', 'Šancová', 'Tupého', 'Jeséniova', 'Čremchová', 'Husova',
     'Koliba'],
    ['Koliba', 'Husova', 'Čremchová', 'Jeséniova', 'Tupého', 'Šancová', 'Štefanovičova', 'Nám. slobody',
     'Hodžovo nám.'],
    ['Hodžovo nám.', 'Kozia', 'Partizánska', 'Zámocká', 'Hrad', 'Inovecká', 'Radvanská', 'Hummelova', 'Červený kríž',
     'Búdková', 'Horský park', 'Vozovňa Hroboňova', 'Lovinského', 'Valašská'],
    ['Valašská', 'Lovinského', 'Vozovňa Hroboňova', 'Horský park', 'Búdková', 'Červený kríž', 'Jančova', 'Radvanská',
     'Inovecká', 'Hrad', 'Zámocká', 'Partizánska', 'Kozia', 'Hodžovo nám.'],
    ['Hlavná stanica', 'SAV', 'Hodžovo nám.', 'Kollárovo nám.', 'Mickiewiczova', 'Odborárske nám.', 'Legionárska',
     'Trnavské mýto', 'Odbojárov', 'Nová doba', 'Polus City Center', 'Odborárska', 'Magnetová', 'Vozovňa Jurajov dvor',
     'PPA Controll', 'Zlaté piesky', 'Kon-Rad', 'Vajnory-nadjazd', 'Pri starom letisku', 'Uhliská', 'MiÚ Vajnory',
     'Hospodárska', 'Vajnory', 'Vajnory-konečná'],
    ['Vajnory-konečná', 'Vajnory', 'Hospodárska', 'MiÚ Vajnory', 'Uhliská', 'Pri starom letisku', 'Vajnory-nadjazd',
     'Kon-Rad', 'Zlaté piesky', 'PPA Controll', 'Jurajov dvor', 'Magnetová', 'Odborárska', 'Zátišie',
     'Polus City Center', 'Nová doba', 'Odbojárov', 'Trnavské mýto', 'Legionárska', 'Americké nám.', 'Kollárovo nám.',
     'Hodžovo nám.', 'SAV', 'Hlavná stanica'],
    ['Hlavná stanica', 'SAV', 'Hodžovo nám.', 'Kollárovo nám.', 'Blumentál', 'Račianske mýto', 'Ursínyho',
     'Pionierska', 'Riazanská', 'Mladá garda', 'Nám. Biely kríž', 'ŽST Vinohrady', 'Vozovňa Krasňany', 'Malé Krasňany',
     'Pekná cesta', 'Černockého', 'Hečkova', 'Bukovinská', 'Trávna-Drevona', 'Púchovská', 'Rybničná', 'OU obchodné',
     'OU železničné', 'Na pantoch'],
    ['Na pantoch', 'OU železničné', 'OU obchodné', 'Rybničná', 'Púchovská', 'Trávna-Drevona', 'Bukovinská', 'Hečkova',
     'Černockého', 'Pekná cesta', 'Malé Krasňany', 'Vozovňa Krasňany', 'ŽST Vinohrady', 'Nám. Biely kríž',
     'Mladá garda', 'Riazanská', 'Pionierska', 'Ursínyho', 'Račianske mýto', 'Povraznícka', 'STU', 'Kollárovo nám.',
     'Hodžovo nám.', 'SAV', 'Hlavná stanica'],
    ['Zlaté piesky', 'Kon-Rad', 'Vajnory-nadjazd', 'Pri starom letisku', 'Športové letisko', 'Lokomotívne depo II',
     'Na pasekách', 'Východné', 'Lokomotívne depo I', 'Sklabinská', 'Pri Šajbách', 'Pastierska', 'Stolárska',
     'Bukovinská', 'Hečkova'],
    ['Hečkova', 'Bukovinská', 'Trávna-Drevona', 'Ihrisková', 'Pastierska', 'Pri Šajbách', 'Sklabinská',
     'Lokomotívne depo I', 'Východné', 'Na pasekách', 'Lokomotívne depo II', 'Športové letisko', 'Pri starom letisku',
     'Vajnory-nadjazd', 'Kon-Rad', 'Zlaté piesky'],
    ['Hlavná stanica', 'SAV', 'Hodžovo nám.', 'Kollárovo nám.', 'Špitálska', 'Ul. Letisko', 'Fatruny', 'Pestovateľská',
     'Avion-IKEA', 'Galvaniho', 'Stará Ivanská', 'Pri zvonici', 'Bulharská', 'Spoločenská', 'Hanácka', 'Slovinská',
     'Trnavská', 'Haburská', 'Solivarská', 'Bratislavská župa', 'Drieňová', 'Mliekárenská', 'Ružová dolina',
     'Trhovisko', 'Dulovo nám.', 'Svätoplukova', 'Autobusová stanica', 'Cintorínska', 'Špitálska', 'Kollárovo nám.',
     'Hodžovo nám.', 'SAV', 'Hlavná stanica'],
    ['Hlavná stanica', 'SAV', 'Hodžovo nám.', 'Kollárovo nám.', 'Mickiewiczova', 'Karadžičova', 'Kvačalova',
     'Saleziáni', 'Slovanet', 'Nemocnica Ružinov', 'Herlianska-OC Retro', 'Tomášikova', 'Súmračná', 'Astronomická',
     'Vrakuňa-záhrady', 'Majerská', 'Šípová', 'Šíravská', 'Estónska', 'Stavbárska', 'Toryská', 'Bodrocká',
     'Korytnická'],
    ['Korytnická', 'Nákupná', 'Učiteľská', 'Ul. 8. mája', 'ŽST P. Biskupice', 'Dudvážska', 'Hronská', 'Toryská',
     'Stavbárska', 'Estónska', 'Šíravská', 'Šípová', 'Majerská', 'Vrakuňa-záhrady', 'Astronomická', 'Súmračná',
     'Tomášikova', 'Herlianska-OC Retro', 'Nemocnica Ružinov', 'Slovanet', 'Saleziáni', 'Kvačalova', 'Karadžičova',
     'Americké nám.', 'Kollárovo nám.', 'Hodžovo nám.', 'SAV', 'Hlavná stanica'],
    ['Hodžovo nám.', 'Kollárovo nám.', 'Špitálska', 'Ul. Čiližská', 'Žitavská', 'Dudvážska', 'Hronská', 'Toryská',
     'Komárovská', 'Priekopnícka', 'Cintorín Vrakuňa', 'Ríbezľová', 'Ondrejovova', 'Brodná',
     'Gagarinova-Rádio Europa 2', 'Hraničná-OC Retro', 'Pažítková', 'Prievozská', 'BBC1 Plus-Miletičova', 'Novohradská',
     'Svätoplukova', 'Autobusová stanica', 'Cintorínska', 'Špitálska', 'Kollárovo nám.', 'Hodžovo nám.'],
    ['Hlavná stanica', 'Nám. Franza Liszta', 'Karpatská', 'Račianske mýto', 'Trnavské mýto', 'Zimný štadión',
     'Bajkalská', 'Sabinovská', 'Trnavská', 'Trnavská-NAD', 'Martinský cintorín', 'Clementisova', 'Ivanská cesta',
     'Súhvezdná', 'Astronomická', 'Súmračná', 'DK Ružinov', 'Nevädzová-OC Retro', 'Kaštieľska', 'MiÚ Ružinov',
     'Hraničná-OC Retro', 'Pažítková', 'Prievozská', 'Prístavný most', 'Lúčna', 'Pálenisko', 'Terminál', 'Čierny les',
     'Vlčie hrdlo'],
    ['Vlčie hrdlo', 'Čierny les', 'Terminál', 'Pálenisko', 'Lúčna', 'Prístavný most', 'Prievozská', 'Hraničná-OC Retro',
     'MiÚ Ružinov', 'Mierová', 'Nevädzová-OC Retro', 'DK Ružinov', 'Súmračná', 'Astronomická', 'Súhvezdná',
     'Ivanská cesta', 'Clementisova', 'Martinský cintorín', 'Trnavská-NAD', 'Trnavská', 'Sabinovská', 'Bajkalská',
     'Zimný štadión', 'Trnavské mýto', 'Račianske mýto', 'Karpatská', 'Nám. Franza Liszta', 'Hlavná stanica'],
    ['Hlavná stanica', 'SAV', 'Hodžovo nám.', 'Zochova', 'Aupark', 'Muchovo nám.', 'Farského', 'Mlynarovičova',
     'Šustekova', 'Bulíkova', 'Ovsištské nám.', 'Ovsište', 'Lachova', 'Starohájska', 'Hrobákova', 'Romanova', 'Markova',
     'Švabinského', 'Jiráskova', 'Kopčany-sídlisko', 'Kopčianska-stred', 'ŽST Petržalka', 'Údernícka-Kúpalisko'],
    ['Údernícka-Kúpalisko', 'ŽST Petržalka', 'Kopčianska-stred', 'Kopčany-sídlisko', 'Jiráskova', 'Švabinského',
     'Markova', 'Romanova', 'Hrobákova', 'Starohájska', 'Lachova', 'Ovsište', 'Ovsištské nám.', 'Bulíkova', 'Šustekova',
     'Bosákova', 'Mlynarovičova', 'Farského', 'Zochova', 'Hodžovo nám.', 'SAV', 'Hlavná stanica'],
    ['Jasovská', 'Žehrianska', 'Slnečnice', 'Jarovce-záhrady', 'Strelnica', 'Píla', 'Jarovce', 'Sady', 'Kovácsova',
     'Vývojová', 'Gerulata', 'Kaštieľ Rusovce', 'ŽST Rusovce', 'Gaštanová aleja', 'Pieskový hon', 'Čunovské jazerá',
     'MiÚ Čunovo', 'Čunovo-námestie', 'Čunovo'],
    ['Čunovo', 'Čunovo-námestie', 'MiÚ Čunovo', 'Čunovské jazerá', 'Pieskový hon', 'Gaštanová aleja', 'Kaštieľ Rusovce',
     'Gerulata', 'Vývojová', 'Kovácsova', 'Sady', 'Jarovce', 'Píla', 'Strelnica', 'Jarovce-záhrady', 'Slnečnice',
     'Jasovská'],
    ['Hlavná stanica', 'SAV', 'Hodžovo nám.', 'Zochova', 'Aupark', 'Dvory', 'Rusovská cesta', 'ŽST Petržalka',
     'VŠ Manažmentu', 'Jiráskova', 'Smolenická', 'Lúky II', 'ZŠ Budatínska', 'Budatínska', 'Lúky V', 'Vyšehradská',
     'Ľubovnianska', 'Bzovícka', 'Žehrianska', 'Jasovská'],
    ['Jasovská', 'Žehrianska', 'Bzovícka', 'Ľubovnianska', 'Vyšehradská', 'Lúky V', 'Budatínska', 'ZŠ Budatínska',
     'Lúky II', 'Smolenická', 'Jiráskova', 'VŠ Manažmentu', 'ŽST Petržalka', 'Rusovská cesta', 'Dvory', 'Aupark',
     'Zochova', 'Hodžovo nám.', 'SAV', 'Hlavná stanica'],
    ['Hlavná stanica', 'SAV', 'Hodžovo nám.', 'Zochova', 'Einsteinova', 'Kremnická', 'Záporožská', 'Gercenova',
     'Hálova', 'Jungmannova', 'Nám. hraničiarov', 'Starohájska', 'Hrobákova', 'Romanova', 'Bradáčova', 'Technopol',
     'Topoľčianska', 'Šintavská', 'Strečnianska', 'Lúčanka', 'Ľubovnianska', 'Bzovícka', 'Betliarska',
     'Vozovňa Petržalka'],
    ['Vozovňa Petržalka', 'Betliarska', 'Bzovícka', 'Ľubovnianska', 'Lúčanka', 'Strečnianska', 'Šintavská',
     'Topoľčianska', 'Technopol', 'Bradáčova', 'Romanova', 'Hrobákova', 'Nám. hraničiarov', 'Jungmannova', 'Hálova',
     'Gercenova', 'Záporožská', 'Kremnická', 'Einsteinova', 'Aupark', 'Zochova', 'Hodžovo nám.', 'SAV',
     'Hlavná stanica'],
    ['Ovsište', 'Ovsištské nám.', 'Bulíkova', 'Šustekova', 'Bosákova', 'Mlynarovičova', 'Farského', 'Nám. hraničiarov',
     'Starohájska', 'Hrobákova', 'Romanova', 'Markova', 'Švabinského', 'Tupolevova', 'Topoľčianska', 'Šintavská',
     'Holíčska', 'Lúky II', 'ZŠ Budatínska', 'Budatínska', 'Znievska', 'Lúčanka', 'Ľubovnianska', 'Bzovícka',
     'Betliarska', 'Vozovňa Petržalka'],
    ['Vozovňa Petržalka', 'Betliarska', 'Bzovícka', 'Ľubovnianska', 'Lúčanka', 'Znievska', 'Budatínska',
     'ZŠ Budatínska', 'Lúky II', 'Holíčska', 'Šintavská', 'Topoľčianska', 'Tupolevova', 'Švabinského', 'Markova',
     'Romanova', 'Hrobákova', 'Nám. hraničiarov', 'Farského', 'Mlynarovičova', 'Šustekova', 'Bulíkova',
     'Ovsištské nám.', 'Ovsište'],
    ['Bratislava hlavná stanica', 'Bratislava-Železná studienka', 'Bratislava-Lamač', 'Devínska Nová Ves',
     'Devínske Jazero', 'zóna Kúty', 'Sekule', 'Moravský Svätý Ján', 'Závod', 'Veľké Leváre', 'Malacky', 'zóna 245',
     'Plavecký Štvrtok', 'Zohor', 'zóna 215', 'Devínske Jazero', 'Devínska Nová Ves', 'Bratislava-Lamač',
     'Bratislava-Železná studienka', 'Bratislava hlavná stanica', 'Bratislava-Nové Mesto'],
    ['Zohor', 'Lábske Jazero zastávka', 'Vysoká pri Morave', 'zóna Záhorská Ves', 'zóna 240', 'Vysoká pri Morave',
     'Lábske Jazero zastávka', 'Zohor'],
    ['Bratislava hlavná stanica', 'Bratislava-Vinohrady', 'Bratislava-Nové Mesto', 'Bratislava-Predmestie',
     'Bratislava-Rača', 'Svätý Jur', 'Pezinok zastávka', 'Pezinok', 'Šenkvice', 'Báhoň', 'Cífer', 'Trnava'],
    ['Trnava', 'Cífer', 'Báhoň', 'Šenkvice', 'Pezinok', 'Pezinok zastávka', 'Svätý Jur', 'Bratislava-Rača',
     'Bratislava-Vinohrady', 'Bratislava hlavná stanica', 'Bratislava-Predmestie', 'Bratislava-Nové Mesto'],
    ['Bratislava hlavná stanica', 'Bratislava-Vinohrady', 'Bratislava-Nové Mesto', 'Bratislava-Predmestie',
     'Bratislava-Vajnory', 'Ivanka pri Dunaji', 'Bernolákovo', 'Veľký Biel', 'Senec', 'Reca'],
    ['Reca', 'Senec', 'Veľký Biel', 'Bernolákovo', 'Ivanka pri Dunaji', 'Bratislava-Vajnory', 'Bratislava-Vinohrady',
     'Bratislava hlavná stanica', 'Bratislava-Predmestie', 'Bratislava-Nové Mesto'],
]


def find_unique_stops():
    new_stops = {}
    for stops in stops_stops:
        for stop in stops:
            if stop not in new_stops:
                new_stops[stop] = set()
            new_stops[stop].update(stops)
    return new_stops


if __name__ == '__main__':
    con = connect(database='gis', host='localhost:65432', user='docker', password='docker')
    cursor = con.cursor()

    for stop, target_stops in find_unique_stops().items():
        for target in target_stops:
            cursor.execute('INSERT INTO mhd VALUES (%s, %s)', [stop, target])
            con.commit()
